const sidebar = {
  "/interview-preparation/": [""],
  "/java/": [
    "",
    {
      text: "基础",
      prefix: "basis/",
      collapsible: true,
      children: [""],
    },
    {
      text: "集合",
      prefix: "collection/",
      collapsible: true,
      children: [""],
    },
    {
      text: "并发",
      prefix: "concurrent/",
      collapsible: true,
      children: ["", "java-concurrency-thread-pool"],
    },
    {
      text: "JVM",
      prefix: "jvm/",
      collapsible: true,
      children: ["", "jvm-g1-vs-cms"],
    },
    {
      text: "IO",
      prefix: "io/",
      collapsible: true,
      children: [""],
    },
    {
      text: "新特性",
      prefix: "new-features/",
      collapsible: true,
      children: [""],
    },
  ],
  "/cs-basics/": [
    "",
    {
      text: "操作系统",
      prefix: "operating-system/",
      collapsible: true,
      children: [""],
    },
    {
      text: "计算机网络",
      prefix: "network/",
      collapsible: true,
      children: [""],
    },
    {
      text: "数据结构",
      prefix: "data-structure/",
      collapsible: true,
      children: [""],
    },
    {
      text: "算法",
      prefix: "algorithms/",
      collapsible: true,
      children: [""],
    },
  ],
  "/database/": [
    "",
    {
      text: "MySQL",
      prefix: "mysql/",
      collapsible: true,
      children: [
        "",
        {
          text: "基础与架构",
          collapsible: true,
          children: [
            "mysql-architecture-sql-execution",
            "mysql-innodb-vs-myisam",
          ],
        },
        {
          text: "数据是怎么存的",
          collapsible: true,
          children: ["mysql-row-format", "mysql-buffer-pool"],
        },
        {
          text: "索引与查询优化",
          collapsible: true,
          children: [
            "mysql-why-bplus-tree",
            "mysql-index-design",
            "mysql-index-invalidation",
            "mysql-explain",
            "mysql-count",
          ],
        },
        {
          text: "事务与并发控制",
          collapsible: true,
          children: [
            "mysql-transaction-isolation",
            "mysql-mvcc-read-view",
            "mysql-locks",
            "mysql-lock-rules",
            "mysql-deadlock",
          ],
        },
        {
          text: "日志与持久化",
          collapsible: true,
          children: ["mysql-logs"],
        },
        {
          text: "工程细节与规范",
          collapsible: true,
          children: [
            "mysql-schema-design",
            "mysql-time-and-primary-key",
            "mysql-auto-increment",
          ],
        },
      ],
    },
    {
      text: "Redis",
      prefix: "redis/",
      collapsible: true,
      children: [
        "",
        {
          text: "数据结构与持久化",
          collapsible: true,
          children: [
            "redis-data-structures",
            "redis-special-data-structures",
            "redis-typical-scenarios",
            "redis-persistence",
            "redis-expire-eviction",
          ],
        },
        {
          text: "线上问题与工程实践",
          collapsible: true,
          children: [
            "redis-bigkey-hotkey",
            "redis-blocking-troubleshooting",
            "redis-memory-fragmentation",
            "redis-configuration-tuning",
            "redis-monitoring-metrics",
          ],
        },
        {
          text: "缓存问题",
          collapsible: true,
          children: [
            "redis-cache-problems",
            "redis-bloom-filter",
            "redis-cache-consistency",
          ],
        },
        {
          text: "高可用与分布式协调",
          collapsible: true,
          children: [
            "redis-high-availability",
            "redis-cluster-details",
            "redis-cluster-operations",
            "redis-replication-troubleshooting",
            "redis-distributed-lock",
          ],
        },
        {
          text: "扩展能力",
          collapsible: true,
          children: [
            "redis-pipeline-lua",
            "redis-rate-limiting",
            "redis-message-queue",
            "redis-delayed-task",
          ],
        },
      ],
    },
    {
      text: "SQL",
      prefix: "sql/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Elasticsearch",
      prefix: "elasticsearch/",
      collapsible: true,
      children: [""],
    },
    {
      text: "MongoDB",
      prefix: "mongodb/",
      collapsible: true,
      children: [""],
    },
  ],
  "/system-design/": [
    "",
    {
      text: "设计基础",
      prefix: "basis/",
      collapsible: true,
      children: [""],
    },
    {
      text: "框架",
      prefix: "framework/",
      collapsible: true,
      children: [""],
    },
    {
      text: "安全",
      prefix: "security/",
      collapsible: true,
      children: [""],
    },
  ],
  "/distributed-system/": [
    "",
    {
      text: "RPC",
      prefix: "rpc/",
      collapsible: true,
      children: [""],
    },
  ],
  "/high-performance/": [""],
  "/high-availability/": [""],
  "/tools/": [
    "",
    {
      text: "Docker",
      prefix: "docker/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Git",
      prefix: "git/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Maven",
      prefix: "maven/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Gradle",
      prefix: "gradle/",
      collapsible: true,
      children: [""],
    },
  ],
  "/ai/": [""],
  "/ai-coding/": [""],
  "/roadmap/": [""],
  "/open-source-project/": [""],
  "/books/": [""],
  "/high-quality-technical-articles/": [""],
  "/about-the-author/": [""],
  "/blog/": [
    "",
    {
      text: "实战记录",
      prefix: "practice/",
      collapsible: true,
      children: ["2026-06-18-r2-media-sync-tutorial"],
    },
    {
      text: "随笔",
      prefix: "essays/",
      collapsible: true,
      children: ["2026-06-16-note-1"],
    },
  ],
  "/category/": [],
  "/tag/": [],
  "/article/": [],
  "/timeline/": [],
  "/star/": [],
};

export default sidebar;
