const sidebar = {
  "/interview-preparation/": [""],
  "/java/": [
    "",
    {
      text: "基础",
      prefix: "basis/",
      collapsible: true,
      children: [""],
    },
    {
      text: "集合",
      prefix: "collection/",
      collapsible: true,
      children: [""],
    },
    {
      text: "并发",
      prefix: "concurrent/",
      collapsible: true,
      children: ["", "java-concurrency-thread-pool"],
    },
    {
      text: "JVM",
      prefix: "jvm/",
      collapsible: true,
      children: ["", "jvm-g1-vs-cms"],
    },
    {
      text: "IO",
      prefix: "io/",
      collapsible: true,
      children: [""],
    },
    {
      text: "新特性",
      prefix: "new-features/",
      collapsible: true,
      children: [""],
    },
  ],
  "/cs-basics/": [
    "",
    {
      text: "操作系统",
      prefix: "operating-system/",
      collapsible: true,
      children: [""],
    },
    {
      text: "计算机网络",
      prefix: "network/",
      collapsible: true,
      children: [""],
    },
    {
      text: "数据结构",
      prefix: "data-structure/",
      collapsible: true,
      children: [""],
    },
    {
      text: "算法",
      prefix: "algorithms/",
      collapsible: true,
      children: [""],
    },
  ],
  "/database/": [
    "",
    {
      text: "MySQL",
      prefix: "mysql/",
      collapsible: true,
      children: ["", "mysql-mvcc-read-view"],
    },
    {
      text: "Redis",
      prefix: "redis/",
      collapsible: true,
      children: ["", "redis-cache-consistency"],
    },
    {
      text: "SQL",
      prefix: "sql/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Elasticsearch",
      prefix: "elasticsearch/",
      collapsible: true,
      children: [""],
    },
    {
      text: "MongoDB",
      prefix: "mongodb/",
      collapsible: true,
      children: [""],
    },
  ],
  "/system-design/": [
    "",
    {
      text: "设计基础",
      prefix: "basis/",
      collapsible: true,
      children: [""],
    },
    {
      text: "框架",
      prefix: "framework/",
      collapsible: true,
      children: [""],
    },
    {
      text: "安全",
      prefix: "security/",
      collapsible: true,
      children: [""],
    },
  ],
  "/distributed-system/": [
    "",
    {
      text: "RPC",
      prefix: "rpc/",
      collapsible: true,
      children: [""],
    },
  ],
  "/high-performance/": [""],
  "/high-availability/": [""],
  "/tools/": [
    "",
    {
      text: "Docker",
      prefix: "docker/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Git",
      prefix: "git/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Maven",
      prefix: "maven/",
      collapsible: true,
      children: [""],
    },
    {
      text: "Gradle",
      prefix: "gradle/",
      collapsible: true,
      children: [""],
    },
  ],
  "/ai/": [""],
  "/ai-coding/": [""],
  "/roadmap/": [""],
  "/open-source-project/": [""],
  "/books/": [""],
  "/high-quality-technical-articles/": [""],
  "/about-the-author/": [""],
  "/blog/": [
    "",
    {
      text: "实战记录",
      prefix: "practice/",
      collapsible: true,
      children: ["2026-06-18-r2-media-sync-tutorial"],
    },
    {
      text: "随笔",
      prefix: "essays/",
      collapsible: true,
      children: ["2026-06-16-note-1"],
    },
  ],
  "/category/": [],
  "/tag/": [],
  "/article/": [],
  "/timeline/": [],
  "/star/": [],
};

export default sidebar;
